#!/usr/bin/env python3

import os
import sys
import nltk



from analyzer import Analyzer
from termcolor import colored
from helpers import get_user_timeline


def main():

    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./smile twitter handle")
        
    #gettweets
    tweets = get_user_timeline(sys.argv[1].lstrip("@"), count=200)
    #print(tweets)
    if tweets == None:
        sys.exit("No Tweets")
        
    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")
    
    # instantiate analyzer & tokenizer
    analyzer = Analyzer(positives, negatives)
    tokenizer = nltk.tokenize.TweetTokenizer()


    
    for tweet in tweets:
        score = 0
        token = tokenizer.tokenize(tweet)
        for word in token:
            score += analyzer.analyze(word)
        if score > 0.0:
            print(colored(str(score) + " " + tweet, "green"))
        elif score < 0.0:
            print(colored(str(score) + " " + tweet, "red"))
        else:
            print(colored(str(score) + " " + tweet, "yellow"))
    #print (score)
        

if __name__ == "__main__":
    main()
